switch:
  - platform: xiaomi_miot_raw
    name: 蓝牙网关插座
    host: 192.168.0.201
    token: 81xxxxxxxxxxxxxxxxxxxxxxxxxxxx02
    mapping:
      switch_status:
        siid: 2
        piid: 1
      temperature:
        siid: 2
        piid: 6
      power:    
        siid: 5
        piid: 6
    params:
      switch_status:
        power_on: True
        power_off: False
      power:
        value_factor: 0.01 # 对应的数值会被乘以0.01，用以适配功率显示

  - platform: xiaomi_miot_raw
    name: 港兴达智能插座
    host: 192.168.0.203
    token: c0xxxxxxxxxxxxxxxxxxxxxxxxxxxxd9
    mapping:
      switch_status:
        siid: 2
        piid: 1
    params:
      switch_status:
        power_on: True
        power_off: False


##############################
#    以下内容仅作示例，现在已经有 switch 的
#    设备不再需要配置sensor了
##############################
# sensor:
#   - platform: xiaomi_miot_raw
#     name: plug
#     host: 192.168.0.201
#     token: 81xxxxxxxxxxxxxxxxxxxxxxxxxxxx02
#     mapping:
#       onoff:
#         siid: 2
#         piid: 1
#       temperature:
#         siid: 2
#         piid: 6
#       power:
#         siid: 5
#         piid: 6
#     sensor_property: power
#     sensor_unit: W
#     scan_interval: 10
#     #取到的功率没有小数点，因此做如下处理
#   - platform: template
#     sensors:
#       rsqpower:
#         friendly_name: "插座功率"
#         unit_of_measurement: 'W'
#         value_template: "{{ states('sensor.plug')|float/100 }}"
        
cover:
  - platform: xiaomi_miot_raw
    name: '晾衣架'
    host: 192.168.0.19
    token: 1fxxxxxxxxxxxxxxxxxxxxxxxxxxxx70
    mapping:
      motor_control:
        siid: 2
        piid: 2
      current_position:
        siid: 2
        piid: 11
      target_position:
        siid: 2
        piid: 13
    params:
      motor_control:
        open: 1
        close: 2
        stop: 0